# Generated by Django 4.2.9 on 2024-01-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='drug',
            name='drug_type',
        ),
        migrations.DeleteModel(
            name='uesrbuy',
        ),
        migrations.DeleteModel(
            name='drug',
        ),
    ]
