# Generated by Django 4.2.9 on 2024-01-25 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_book_type_remove_drug_drug_type_delete_uesrbuy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_type',
            old_name='email',
            new_name='description',
        ),
    ]
