# Generated by Django 4.2.9 on 2024-01-25 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_book_books_book_manga_book_novel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_books',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book_manga',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book_novel',
            name='description',
        ),
    ]
